@baseUrl = http://localhost:8081

###
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Cobb"
}

###
GET {{baseUrl}}/users

###
GET {{baseUrl}}/users?name=ga

###
GET {{baseUrl}}/users/3

###
PUT {{baseUrl}}/users/1
Content-Type: application/json

{
    "name": "Anne"
}

###
DELETE {{baseUrl}}/user/25

###
